"""
EMODL file validation utilities
"""
import re
from typing import Tuple, List, Optional


# Note this file was largely generated by AI assistance and then refined.

def is_valid_emodl(content: str) -> Tuple[bool, Optional[str]]:
    """
    Validate if a string represents a valid EMODL file.
    
    Args:
        content: The EMODL file content as a string
        
    Returns:
        Tuple of (is_valid: bool, error_message: Optional[str])
    """
    if not content or not content.strip():
        return False, "Empty EMODL content"
    
    try:
        # Remove comments and normalize whitespace
        normalized = _normalize_emodl(content)
        
        # Check for required structure
        validation_checks = [
            _has_model_block,
            _has_valid_parentheses,
            _has_required_sections,
            _has_valid_syntax
        ]
        
        for check in validation_checks:
            is_valid, error = check(normalized)
            if not is_valid:
                return False, error
                
        return True, None
        
    except Exception as e:
        return False, f"Parse error: {str(e)}"


def _normalize_emodl(content: str) -> str:
    """Remove comments and normalize whitespace"""
    # Remove line comments (starting with ;)
    lines = []
    for line in content.split('\n'):
        # Find semicolon that's not in a string
        in_string = False
        comment_pos = None
        for i, char in enumerate(line):
            if char == '"' and (i == 0 or line[i-1] != '\\'):
                in_string = not in_string
            elif char == ';' and not in_string:
                comment_pos = i
                break
        
        if comment_pos is not None:
            line = line[:comment_pos]
        lines.append(line.strip())
    
    return ' '.join(lines).strip()


def _has_model_block(content: str) -> Tuple[bool, Optional[str]]:
    """Check for start-model and end-model blocks"""
    start_pattern = r'\(\s*start-model\s+["\']?[\w\-_.]+["\']?\s*\)'
    end_pattern = r'\(\s*end-model\s*\)'
    
    if not re.search(start_pattern, content, re.IGNORECASE):
        return False, "Missing (start-model ...) declaration"
    
    if not re.search(end_pattern, content, re.IGNORECASE):
        return False, "Missing (end-model) declaration"
    
    return True, None


def _has_valid_parentheses(content: str) -> Tuple[bool, Optional[str]]:
    """Check for balanced parentheses"""
    paren_count = 0
    in_string = False
    
    for i, char in enumerate(content):
        if char == '"' and (i == 0 or content[i-1] != '\\'):
            in_string = not in_string
        elif not in_string:
            if char == '(':
                paren_count += 1
            elif char == ')':
                paren_count -= 1
                if paren_count < 0:
                    return False, "Unmatched closing parenthesis"
    
    if paren_count != 0:
        return False, f"Unbalanced parentheses (missing {paren_count} closing)"
    
    return True, None


def _has_required_sections(content: str) -> Tuple[bool, Optional[str]]:
    """Check for at least some basic required elements"""
    # At minimum, should have some species or parameters
    required_patterns = [
        (r'\(\s*species\s+\w+', "At least one species declaration"),
        # Could also check for reactions, but not all models need them immediately
    ]
    
    for pattern, description in required_patterns:
        if not re.search(pattern, content, re.IGNORECASE):
            return False, f"Missing {description}"
    
    return True, None


def _has_valid_syntax(content: str) -> Tuple[bool, Optional[str]]:
    """Basic syntax validation for common EMODL constructs"""
    # Check for malformed common constructs
    malformed_patterns = [
        (r'\(\s*species\s*\)', "Empty species declaration"),
        (r'\(\s*param\s*\)', "Empty parameter declaration"),  
        (r'\(\s*reaction\s*\)', "Empty reaction declaration"),
        (r'\(\s*observe\s*\)', "Empty observe declaration"),
    ]
    
    for pattern, error_msg in malformed_patterns:
        if re.search(pattern, content, re.IGNORECASE):
            return False, f"Malformed syntax: {error_msg}"
    
    return True, None


def extract_model_name(content: str) -> Optional[str]:
    """Extract model name from EMODL content"""
    pattern = r'\(\s*start-model\s+["\']?([\w\-_.]+)["\']?\s*\)'
    match = re.search(pattern, content, re.IGNORECASE)
    return match.group(1) if match else None


def get_emodl_summary(content: str) -> dict:
    """Get a summary of EMODL content for metadata"""
    summary = {
        "model_name": extract_model_name(content),
        "species_count": len(re.findall(r'\(\s*species\s+\w+', content, re.IGNORECASE)),
        "parameter_count": len(re.findall(r'\(\s*param\s+\w+', content, re.IGNORECASE)),
        "reaction_count": len(re.findall(r'\(\s*reaction\s+\w+', content, re.IGNORECASE)),
        "observation_count": len(re.findall(r'\(\s*observe\s+\w+', content, re.IGNORECASE)),
    }
    return summary


# Example usage and testing
if __name__ == "__main__":
    # Test with a simple valid EMODL
    test_emodl = """
    (import (rnrs) (emodl cmslib))
    
    (start-model "test_model")
    
    (species S 1000)
    (species I 10)
    
    (param beta 0.3)
    
    (reaction infection (S) (I) (* beta S I) 0)
    
    (observe susceptible S)
    (observe infected I)
    
    (end-model)
    """
    
    is_valid, error = is_valid_emodl(test_emodl)
    print(f"Valid: {is_valid}")
    if error:
        print(f"Error: {error}")
    else:
        print(f"Summary: {get_emodl_summary(test_emodl)}")